spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.qecjtdkaknvncgiztrqp
    password: kSPi2MI8BDScCV0M
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2  # 🔴 Very important: reduce pool size!
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: my_app_schema
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: emprux1@gmail.com
    password: vbsuxtijxsekzfiw
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
            required: true
        connectiontimeout: 5000
        timeout: 300
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: f3aae0de17fa48c74b1378fde245afd3ad7b0588492d131400e84e3226fc8e1c
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

eduflow:
  mail : emprux1@gmail.com

